#!/bin/bash
set -e

# $1 = "remove" or "purge"
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    udevadm control --reload-rules
    udevadm trigger --subsystem-match=hidraw --attr-match=idVendor=256f || true
    pkill -HUP -f "systemd --user" || true
fi

exit 0